version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  postgres_app:
    build: 
      network: host
      context: ./
      dockerfile: dockerfile

    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/mydb?schema=public
    depends_on:
      - postgres